### ISSUE TITLE
long script filter build time

### ISSUE THREAD

**Issue by itsbrex** [whomwah/alfred-vscode-workflow#2]
I have ~330 git repos in `~github` and for whatever reason the workflow lags for 5-10 seconds beofre returning the json object list, but then any keystroke retriggers the script filter. 

Here's a gif: https://share.cleanshot.com/tSDU4JXaTVBCeg0bpFdx

I tried with the `main` branch that is two commits ahead of the latest release & building from source but no luck on either.

macOS 13.0 (22A380)

**Comment by whomwah** [comment]
Gah, that’s a shame. I’ve not tried with that many projects I’m afraid so never had the issue. But this is super useful to know as I’m sure you’re not alone.

Think I may create a branch and go the same SQLite route that I did with the Github workflow. This works really well for lots of data.

In the mean time I’ll update the README with a warning.

**Comment by whomwah** [comment]
Out of interest do you see the same lag when running `findd -q .git ~github` from the terminal ? and does it do the same when you restrict the search slightly e.g `findd -q .git ~github/foo ~github/bar`?

**Comment by whomwah** [comment]
I did a little test myself by creating 400 more `.git` repos and `findd` is fetching them pretty much instantly. I'm on a fast M1 machine but I'm interested to know where the bottle neck is here.

![findd](https://user-images.githubusercontent.com/2031/201873830-9d6b00d6-09ab-4cc2-89d6-6f919400eb95.gif)

**Comment by whomwah** [comment]
A new release to try that adds new config settings and caches the search results:

* https://github.com/whomwah/alfred-vscode-workflow/releases/latest

**Comment by itsbrex** [comment]
@whomwah sorry this took so long to get back to, but all is working! You da man.
